### PR TITLE
fixes #317

### LINKED ISSUE #317: Show predictions on old sondes
It looks like we hide predictions when there's been no new data and the alt is less than 600m, however this might not be where the sonde finally lands.

Do we even want to hide predictions for landed sondes? The predictor tries pretty hard to not generate bogus landed predictions so it might be safe to remove this logic (plus other places?) not sure?

https://github.com/projecthorus/sondehub-tracker/blob/master/js/tracker.js#L1707

### PR DESCRIPTION
**Pull request by smwnwrght**
Reinstates landing predictions for landed sondes.

I have tested this but would appreciate a review as I don't understand the other code in updatePredictions() - hence draft pull request!

### CODE REVIEW

**Comment by TheSkorm** [comment]
Thanks @smwnwrght. Can you please remove the white space changes from the PR so that it's only the relevant code changes?

@darksidelemm this will show the predictions all the time, even after landed - not sure if we came to a conclusion as to if that was a good idea or not?

**Comment by darksidelemm** [comment]
I think this should be merged into the testing branch so we can check the behaviour out for a while.

**Comment by smwnwrght** [comment]
@TheSkorm have reverted whitespace (and cleaned up my code!)

**Comment by smwnwrght** [comment]
@darksidelemm Should I change this to the testing branch?

**Comment by darksidelemm** [comment]
Yes, I think it should be possible for you to re-target this to the testing branch. I've just made sure testing is in line with the master branch.

**Comment by smwnwrght** [comment]
@darksidelemm I have updated this to merge with the testing branch

**Comment by darksidelemm** [comment]
OK, I'll merge this in. it will be visible at testing.v2.sondehub.org

**Pull request merged**
